[templates."OPPO Find X8 Ultra"]
manufacturer = "OPPO"
brand = "OPPO"
model = "PKJ110"
device = "PKJ110"
product = "PKJ110"
fingerprint = "oppo/PKJ110/PKJ110:15/AP3A.240617.008/1758264862075:user/release-keys"
marketname = "Find X8 Ultra"
author = "GitHub@Seyud"
