[templates."Xiaomi 17 Ultra"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2512BPNDAC"
device = "nezha"
product = "nezha"
fingerprint = ""
name = "nezha"
marketname = "Xiaomi 17 Ultra"
author = "Github@orangesroof"