[templates.IQOO_13]
manufacturer = "vivo"
brand = "vivo"
model = "V2408A"
device = "V2408A"
product = "V2408A"
fingerprint = ""
name = "PD2408"
marketname = "VIVO IQOO 13"
author = "GitHub@qianxiao1234"
description = "特点：王者144帧"
